watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ["Odyssey G5"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 9
      left: 9
      bottom: 9
      right: 9
    widgets:
      left: ["glazewm_workspaces", "apps"]
      center: ["active_window"]
      right:
        [
          "media",
          "cpu",
          "memory",
          "disk",
          "volume",
          "notifications",
          "power_menu",
        ]
widgets:
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: false
      hide_if_offline: false
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf4bc</span> Tot {info[percent][total]}% · Frq {info[freq][current]:.2f} MHz"
      update_interval: 2000
      histogram_icons:
        - '\u2581'
        - '\u2581'
        - '\u2582'
        - '\u2583'
        - '\u2584'
        - '\u2585'
        - '\u2586'
        - '\u2587'
        - '\u2588'
      callbacks:
        on_right: "exec cmd /c Taskmgr"
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uf4bc</span> {virtual_mem_free}/{virtual_mem_total}"
      label_alt: "<span>\uf4bc</span> VIRT: {virtual_mem_percent}% SWAP: {swap_mem_percent}%"
      update_interval: 10000
      callbacks:
        on_right: "exec cmd /c Taskmgr"
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{artist}"
      max_field_size:
        label: 25
        label_alt: 25
      show_thumbnail: true
      controls_hide: false
      hide_empty: true
      thumbnail_alpha: 80
      thumbnail_padding: 8
      thumbnail_corner_radius: 6
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "{win[process][name]} hwnd={win[hwnd]}"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 36
      max_length_ellipsis: "..."
      monitor_exclusive: true
      ignore_window:
        classes: []
        processes:
          - ShellExperienceHost.exe
          - ShellHost.exe
          - StartMenuExperienceHost.exe
        titles: []

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span>"
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_middle: "exec cmd.exe /c start ms-settings:sound"
        on_right: "exec quick_settings"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%d %b, %H:%M}"
      timezones: []
  disk:
    type: "yasb.disk.DiskWidget"
    options:
      label: "<span>\uf0c7</span>"
      label_alt: "<span>\uf0c7</span>"
      update_interval: 60
      group_label:
        volume_labels: ["C", "G"]
        show_label_name: false
        blur: True
        round_corners: True
        round_corners_type: "small"
        border_color: "System"
        alignment: "right"
        direction: "down"
        distance: 6
      callbacks:
        on_left: "toggle_group"
        on_middle: "toggle_label"
        on_right: "exec explorer C:\\"
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span>"
      label_alt: "{count} notifications"
      hide_empty: false
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - { icon: "File", launch: "explorer" }
        - { icon: "Terminal", launch: "wt" }
        - {
            icon: "Code",
            launch: "C:\\Users\\WaYy\\AppData\\Local\\Programs\\VSCodium\\VSCodium.exe",
          }
  app_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span>\uf40e</span>"
      label_alt: "<span>\uf40e</span>"
      class_name: "app-button"
      callbacks:
        on_left: "exec start_menu"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 3
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["\udb81\udf3a", "Cancel"]
